<a href="https://colab.research.google.com/github/PrantoDas/Spring-2022-Software-Project-IV/blob/task%2Fteam-1/Copy_of_22_09_22_online_DM_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/iris.csv")
df.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa

In [ ]:
x = df.drop('species',axis=1)
x.head(5)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.4           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.3          0.2
4           5.1          3.6           1.4          0.2

In [ ]:
y = df['species']
y.head(5)

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [ ]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
l = LabelEncoder()
y = l.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
y_test

array([0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 1, 2,
       1, 2, 2, 1, 0, 2, 2, 0])

Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lrg = LinearRegression()
lrg.fit(x_train,y_train)
lrg.score(x_train,y_train)*100

91.7431049367521

In [ ]:
lrg.score(x_test,y_test)*100

96.40130965257534

In [ ]:
y_pred_lrg=lrg.predict(x_test)

In [ ]:
y_pred_lrg

array([-0.01214775,  1.86627455,  1.70910588,  1.57937178, -0.05288301,
       -0.01397355, -0.09196098,  2.11171829, -0.04398125,  0.9174777 ,
        0.01021419,  1.77000769, -0.04551764,  2.21747387,  0.09170616,
        1.6938199 ,  1.95360365,  0.224167  ,  1.66293394, -0.08967726,
        0.9025343 ,  1.73500407,  0.87807516,  1.84884721,  1.96577926,
        1.0518977 , -0.04923141,  1.67045882,  2.01774415, -0.0859725 ])

In [ ]:
y_test

array([0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 1, 2,
       1, 2, 2, 1, 0, 2, 2, 0])

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lgrg = LogisticRegression()
lgrg.fit(x_train,y_train)
y_train_prediction = lgrg.predict(x_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
training_data_accuracy = accuracy_score(y_train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy*100)